### PR TITLE
Unit tests

### PR DESCRIPTION
**Pull request by IvanOleksiyuk**
I try adding unit tests to cover all the code in this repo

### CODE REVIEW

**Comment by samvanstroud** [comment]
This is great to see! we can also slowly add tests in separate MRs to prevent divergence. It would be good to add the coverage bits too.

Was there a reason to prefer unittest over pytest? I wonder if we should stick with pytest for consistency with salt and atlas-ftag-tools

**Comment by IvanOleksiyuk** [comment]
I was using unittest for consistency with umami and because pytest also can run unittests but not the other way around. I can change them to pytests if you like.
Could you elaborate on coverage bits? I use "coverage" to check the coverage and I can add the report from it in each of the PR's with tests is that ok or should we do something with CI that runs tests and checks the coverage with every commit?

**Comment by IvanOleksiyuk** [comment]
`Name                                  Stmts   Miss  Cover
---------------------------------------------------------
upp/__init__.py                           1      0   100%
upp/classes/__init__.py                   0      0   100%
upp/classes/components.py               147     11    93%
upp/classes/preprocessing_config.py      78      2    97%
upp/classes/region.py                    12      1    92%
upp/classes/resampling_config.py         28      0   100%
upp/classes/variable_config.py           36      2    94%
upp/logger.py                            13      0   100%
upp/main.py                              69     31    55%
upp/stages/hist.py                       52      3    94%
upp/stages/interpolation.py              37      0   100%
upp/stages/merging.py                    74      2    97%
upp/stages/normalisation.py             110     32    71%
upp/stages/plot.py                       37      2    95%
upp/stages/resampling.py                167     35    79%
upp/utils.py                              2      0   100%
---------------------------------------------------------
TOTAL                                   863    121    86%`

**Comment by IvanOleksiyuk** [comment]
image

**Comment by samvanstroud** [comment]
Looks very promising, thanks Ivan! can you also add a workflow to run these tests as Github actions? Something similar to the block here should do the trick https://github.com/umami-hep/atlas-ftag-tools/blob/main/.github/workflows/testing.yml#L35

**Comment by IvanOleksiyuk** [comment]
I added an integration test that is based on the ftag.mock data (it wasn't easy). Most of the functionality is covered by this test 
Some parts have additional unit tests but not all

**Comment by IvanOleksiyuk** [comment]
I'll try adding them to github

**Comment by IvanOleksiyuk** [comment]
Seems to work now

**Comment by samvanstroud** [comment]
Looks great! merging this now

**Pull request merged**
